### ISSUE TITLE
Add a sub-topic to an article [3]

### ISSUE THREAD

**Issue by nicchunglow** [snaphunters/snapi#9] opened 2020-02-28 06:21 UTC
## User Story

**AS A** Content Creator
**I WANT TO** be able to add sub-topic to my articles
**SO THAT** my articles are searchable by sub-topic. 

## Acceptance Criteria

**GIVEN** that I have already in add article mode after clicking the add article button, 
**WHEN** I want to add a sub-topic
**THEN** I am able to input the sub-topic and wait to be saved.

**Comment by Jonwyp** [comment] 2020-03-05 08:46
Closed. Duplicate of #31

**Closed as completed by Jonwyp** 2020-03-05 08:46 UTC
Labels: user story
